services:
  sonarqube_db:
    container_name: 'sonarqube_db'
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=sonarqube
      - POSTGRES_DB=sonarqube
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube:9.8-community
    container_name: sonarqube
    depends_on:
      - sonarqube_db
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: mypassword
      # Optional: enable IPv6
      # JAVA_TOOL_OPTIONS: "-Djava.net.preferIPv6Addresses=true"
      # SONAR_WEB_JAVAADDITIONALOPTS: "-Djava.net.preferIPv6Addresses=true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_temp:/opt/sonarqube/temp
volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_temp:
  postgres_data: