apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
  namespace: k8s-sdi
  labels:
    app: url-shortener
spec:
  selector:
    app: url-shortener
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4567
