apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-app
  namespace: k8s-sdi
  labels:
    app: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener-app
          image: djaniga/08-url-shortener:latest
          ports:
            - containerPort: 8082