apiVersion: v1
kind: Service
metadata:
  name: 08-url-shortener
  namespace: k8s-program
spec:
  selector:
    app: 08-url-shortener
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
