apiVersion: v1
kind: Service
metadata:
  name: url-shortener-db-service
  namespace: k8s-program
  labels:
    database: url-shortener-db
spec:
  type: ClusterIP
  selector:
    database: url-shortener-db
  ports:
    - port: 83
      targetPort: 8083