apiVersion: v1
kind: Service
metadata:
  name: url-shortener-db-service
  namespace: k8s-sdi
  labels:
    database: url-shortener-db
spec:
  type: ClusterIP
  selector:
    database: url-shortener-db
  ports:
    - port: 5432
      targetPort: 5432