services:
  url_shortener_db:
    container_name: 'url_shortener_db'
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=testuser
      - POSTGRES_DB=urls
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
  redis:
    image: redis:8.0.1
    container_name: redis-server
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --save 20 1 
      --loglevel warning
      --maxmemory 512mb 
      --maxmemory-policy allkeys-lru 
      --appendonly yes
#      --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    restart: always

volumes:
    cache:
      driver: local