/*
 * This file is generated by jOOQ.
 */
package data.tables.records;


import data.tables.Notifications;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NotificationsRecord extends UpdatableRecordImpl<NotificationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.notifications.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.notifications.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.notifications.service_name</code>.
     */
    public void setServiceName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.notifications.service_name</code>.
     */
    public String getServiceName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.notifications.types</code>.
     */
    public void setTypes(String[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.notifications.types</code>.
     */
    public String[] getTypes() {
        return (String[]) get(2);
    }

    /**
     * Setter for <code>public.notifications.sender</code>.
     */
    public void setSender(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.notifications.sender</code>.
     */
    public String getSender() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.notifications.recipients_ids</code>.
     */
    public void setRecipientsIds(String[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.notifications.recipients_ids</code>.
     */
    public String[] getRecipientsIds() {
        return (String[]) get(4);
    }

    /**
     * Setter for <code>public.notifications.title</code>.
     */
    public void setTitle(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.notifications.title</code>.
     */
    public String getTitle() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.notifications.message</code>.
     */
    public void setMessage(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.notifications.message</code>.
     */
    public String getMessage() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationsRecord
     */
    public NotificationsRecord() {
        super(Notifications.NOTIFICATIONS);
    }

    /**
     * Create a detached, initialised NotificationsRecord
     */
    public NotificationsRecord(Integer id, String serviceName, String[] types, String sender, String[] recipientsIds, String title, String message) {
        super(Notifications.NOTIFICATIONS);

        setId(id);
        setServiceName(serviceName);
        setTypes(types);
        setSender(sender);
        setRecipientsIds(recipientsIds);
        setTitle(title);
        setMessage(message);
        resetTouchedOnNotNull();
    }
}
