/*
 * This file is generated by jOOQ.
 */
package data;


import org.jooq.Sequence;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>public.notification_id_seq</code>
     */
    public static final Sequence<Long> NOTIFICATION_ID_SEQ = Internal.createSequence("notification_id_seq", Public.PUBLIC, DSL.comment(""), SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
